export const COOKIE_BEARER_TOKEN = "@BEARER_TOKEN"
export const COOKIE_SELECTED_RESTAURANT_DOMAIN = "@SELECTED_RESTAURANT_DOMAIN"
export const COOKIE_SELECTED_MENU_ID = "@COOKIE_SELECTED_MENU_ID"
export const COOKIE_SELECTED_MENU_URLPATH = "@COOKIE_SELECTED_MENU_URLPATH"